export const screens = [
    {
      id: 1,
      title: "Homepage",
      color: "#FF4500",
      typeIcon: "1",
      icon: "home",
      link: "Home",
    },
    {
      id: 2,
      title: "Text page",
      color: "#87CEEB",
      typeIcon: "2",
      icon: "text",
      link: "TextPage",
    },
    {
      id: 3,
      title: "Gallery",
      color: "#4682B4",
      typeIcon: "1",
      icon: "photo",
      link: "Gallery",
    },
    {
      id: 4,
      title: "Products",
      color: "#6A5ACD",
      typeIcon: "2",
      icon: "shopping-cart",
      link: "Products",
    },
    {
      id: 5,
      title: "Form",
      color: "#FF69B4",
      typeIcon: "3",
      icon: "form",
      link: "Form",
    },
    {
      id: 6,
      title: "Map",
      color: "#adbc0c",
      typeIcon: "2",
      icon: "map",
      link: "Map",
    },
    {
      id: 7,
      title: "Chat",
      color: "#00BFFF",
      typeIcon: "2",
      icon: "chat",
      link: "Chat",
    },
    {
      id: 8,
      title: "List",
      color: "#f37e00",
      typeIcon: "4",
      icon: "align-justify",
      link: "List",
    },
    {
      id: 9,
      title: "Login",
      color: "#ff0000",
      typeIcon: "6",
      icon: "login-variant",
      link: "Login",
    },
    {
      id: 10,
      title: "Profile (Protected page)",
      color: "#191970",
      typeIcon: "2",
      icon: "lock",
      link: "ProtectedPage",
    },
    {
      id: 11,
      title: "Theme settings",
      color: "#20B2AA",
      typeIcon: "5",
      icon: "settings-sharp",
      link: "Theme",
    },
    {
      id: 12,
      title: "News",
      color: "#FF4500",
      typeIcon: "2",
      icon: "text",
      link: "News",
    },
  ];