export const screens = [
  {
    id: 1,
    title: "Homepage",
    color: "#4682B4",
    typeIcon: "1",
    icon: "home",
    link: "Home",
  },
  {
    id: 2,
    title: "Text page",
    color: "#4682B4",
    typeIcon: "2",
    icon: "text",
    link: "TextPage",
  },
  {
    id: 3,
    title: "Gallery",
    color: "#4682B4",
    typeIcon: "1",
    icon: "photo",
    link: "Gallery",
  },
  {
    id: 4,
    title: "Products",
    color: "#4682B4",
    typeIcon: "2",
    icon: "shopping-cart",
    link: "Products",
  },
  {
    id: 5,
    title: "Form",
    color: "#4682B4",
    typeIcon: "3",
    icon: "form",
    link: "Form",
  },
  {
    id: 6,
    title: "Map",
    color: "#4682B4",
    typeIcon: "2",
    icon: "map",
    link: "Map",
  },
  {
    id: 7,
    title: "Chat",
    color: "#4682B4",
    typeIcon: "2",
    icon: "chat",
    link: "Chat",
  },
  {
    id: 8,
    title: "List",
    color: "#4682B4",
    typeIcon: "4",
    icon: "align-justify",
    link: "List",
  },
  {
    id: 8,
    title: "Comments",
    color: "#4682B4",
    typeIcon: "1",
    icon: "commenting",
    link: "Comments",
  },
  {
    id: 9,
    title: "Login",
    color: "#4682B4",
    typeIcon: "6",
    icon: "login-variant",
    link: "Login",
  },
  {
    id: 10,
    title: "Profile (Protected page)",
    color: "#4682B4",
    typeIcon: "2",
    icon: "lock",
    link: "ProtectedPage",
  },
  {
    id: 11,
    title: "Menu",
    color: "#4682B4",
    typeIcon: "4",
    icon: "align-justify",
    link: "Menu",
  },
  {
    id: 12,
    title: "Theme settings",
    color: "#4682B4",
    typeIcon: "5",
    icon: "settings-sharp",
    link: "Theme",
  },
  {
    id: 13,
    title: "News",
    color: "#4682B4",
    typeIcon: "2",
    icon: "text",
    link: "News",
  },
];
